# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Amil
                                 A QGIS plugin
 Um assistente para criar mapas interativos no navegador utilizando Leaflet
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-12-20
        copyright            : (C) 2021 by Givaldo Cesar/Codevasf-1SR
        email                : givaldocesar@live.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Amil class from file Amil.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .amil import Amil
    return Amil(iface)
